name: sloth
description: serverless functions for pack_poc
publish_to: none

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies: 
  functions_framework: ^0.4.1
  shelf: ^1.1.4

dev_dependencies:
  build_runner: ^2.0.4
  effective_dart: ^1.3.1
  http: ^0.13.3
  test: ^1.17.5
  test_process: ^2.0.0
